# Generated by Django 5.2 on 2025-04-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
